#!/usr/bin/env python3
"""JH4: export the v7 HEAD to pure Swift + parity fixtures.

The deployed smoother is 149 floats (r1: 16x3+16, r2: 5x16+5) on a
16x6 ring — orders of magnitude below the ANE dispatch floor, so the
iPhone port is pure Swift on CPU. The mlpackage remains the Mac-side
reference artifact; THIS file is the bridge that keeps the two
byte-identical at the weight level (float32 values embedded exactly).

Emits:
  ../../Tesseract/Tesseract/JepaHWeights.swift   (constants)
  fixtures_head.json                              (8 val rings, float64 forward)
"""

import json
import numpy as np

W = np.load("jepa_weights.npz")
R1 = W["head.r1.weight"].astype(np.float32)   # [16,3]
R1b = W["head.r1.bias"].astype(np.float32)    # [16]
R2 = W["head.r2.weight"].astype(np.float32)   # [5,16]
R2b = W["head.r2.bias"].astype(np.float32)    # [5]


def lit(a):
    """Swift array literal from float32 values, exact via repr of the
    float64 promotion (float32 -> double is exact)."""
    return "[" + ", ".join(repr(float(x)) for x in a.flatten()) + "]"


swift = f"""// GENERATED by nn/jepa/export_swift.py — do not edit.
// JEPA-H v7 head weights (commit eb4ead9 training run), float32
// values promoted exactly to Double. 149 numbers: the ENTIRE
// deployed model — a hypernet from ring autocorrelations to a
// symmetric 5-tap kernel + jump gate. No slot-content parameters
// exist (the structural no-memorization law).

enum JepaHWeights {{
    static let r1w: [Double] = {lit(R1)}      // [16][3] row-major
    static let r1b: [Double] = {lit(R1b)}
    static let r2w: [Double] = {lit(R2)}      // [5][16] row-major
    static let r2b: [Double] = {lit(R2b)}
}}
"""
open("../../Tesseract/Tesseract/JepaHWeights.swift", "w").write(swift)
print("  wrote JepaHWeights.swift "
      f"({R1.size + R1b.size + R2.size + R2b.size} floats)")


# ── float64 reference forward (mirrors build_model.np_forward) ──
def np_forward(y):
    from math import erf, sqrt
    gelu = np.vectorize(lambda x: 0.5 * x * (1 + erf(x / sqrt(2))))
    mu = y.mean(0, keepdims=True)
    sd = y.std(0, keepdims=True) + 1e-12
    yw = (y - mu) / sd
    def rsh(x, k): return np.roll(x, -k, axis=0)
    regime = np.stack([(yw * rsh(yw, lag)).mean(0) for lag in (1, 2, 3)],
                      axis=1)
    h = gelu(regime @ R1.T.astype(np.float64) + R1b.astype(np.float64))
    p = h @ R2.T.astype(np.float64) + R2b.astype(np.float64)
    ex = np.exp(p[:, :3] - p[:, :3].max(1, keepdims=True))
    a = ex / ex.sum(1, keepdims=True)
    gs = np.log1p(np.exp(p[:, 3]))
    gb = p[:, 4]
    yp1, ym1 = rsh(yw, 1), rsh(yw, -1)
    yp2, ym2 = rsh(yw, 2), rsh(yw, -2)
    smooth = a[:, 0] * yw + 0.5 * a[:, 1] * (yp1 + ym1) \
        + 0.5 * a[:, 2] * (yp2 + ym2)
    d = np.abs(yw - 0.5 * (yp1 + ym1))
    g = 1 / (1 + np.exp(-(gs * d + gb)))
    sw = (1 - g) * smooth + g * yw
    return sw * sd + mu


caps = [json.loads(l) for l in open("corpus/trajectories.jsonl")]
fixtures = []
for c in caps[-8:]:
    y = np.array(c["obs"], dtype=np.float64)
    fixtures.append({"y": y.tolist(), "shat": np_forward(y).tolist()})
json.dump(fixtures, open("fixtures_head.json", "w"))
print(f"  wrote fixtures_head.json ({len(fixtures)} rings)")
