#!/usr/bin/env python3
"""
Emit the CORE AI into the app: generated Swift for the grounded gene
machine (Daniel's placement ruling, 2026-08-11).

Generates:
  Tesseract/Tesseract/SKGeneWeights.swift   frozen weights (ground E,
      passer predictor, token table) + the CURATED gene set + attractor
      latents. Weights ship as one base64 Float32-LE blob (large Swift
      array literals stall the type-checker); small index arrays are
      plain literals.
  TesseractTests/SKGeneFixtures.swift       float32 parity fixtures
      computed here from the SAME weights — the Swift port must match
      (the CPU-twin-is-the-law discipline).

Curation (deterministic, phase law of doc §5):
  ORDER    64 genes, halt ∈ {1,2}, distinct normal forms, lowest ids
  BOUNDARY 32 genes, halt ∈ 3..15, distinct normal forms, lowest ids
  CHAOS     2 genes (the divergers)
Attractors: latents of every selected normal-form class.

Run:  /opt/homebrew/bin/python3 emit_swift.py
"""

import base64
import os

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))          # repo root
APP = os.path.join(ROOT, "Tesseract", "Tesseract")
TESTS = os.path.join(ROOT, "TesseractTests")

GW = dict(np.load(os.path.join(HERE, "ground_weights.npz")).items())
PW = dict(np.load(os.path.join(HERE, "weights.npz")).items())
GT = dict(np.load(os.path.join(HERE, "gene_table.npz")).items())

D, T = 24, 16


def curate():
    halt, nf = GT["halt"], GT["nf"]
    picked, seen = [], set()
    for lo, hi, want, phase in [(1, 2, 64, 0), (3, 15, 32, 1)]:
        got = 0
        for g in range(len(halt)):
            if lo <= halt[g] <= hi and nf[g] not in seen:
                seen.add(int(nf[g])); picked.append((g, phase)); got += 1
                if got == want:
                    break
    # halt == -1 covers both t=0 genes (absent from the corpus) and
    # the 2 divergers; only the divergers run all 16 steps
    for g in np.where((halt == -1) & (GT["act"].sum(axis=1) == 16))[0]:
        picked.append((int(g), 2))
    return picked


def main():
    picked = curate()
    ids = [g for g, _ in picked]
    phases = [p for _, p in picked]
    nfs = [int(GT["nf"][g]) for g in ids]
    halts = [int(GT["halt"][g]) for g in ids]
    att_nf = sorted({n for n in nfs if n >= 0})
    att = GT["attract"][att_nf].astype(np.float32)

    # ── the blob: order matters, layout documented in Swift ─────────
    parts = [
        ("gW1", GW["w1"]), ("gB1", GW["b1"]), ("gW2", GW["w2"]),
        ("gB2", GW["b2"]), ("gW3", GW["w3"]), ("gB3", GW["b3"]),
        ("fMean", GW["fmean"]), ("fStd", GW["fstd"]),
        ("pW1", PW["pw1"]), ("pB1", PW["pb1"]),
        ("pW2", PW["pw2"]), ("pB2", PW["pb2"]),
        ("tokS", PW["tok"][0]), ("tokK", PW["tok"][1]),
        ("attractors", att),
        ("geneZ0", GT["z0"][ids].astype(np.float32)),
        ("geneAct", GT["act"][ids].astype(np.float32)),
    ]
    flat = np.concatenate([p.astype(np.float32).ravel() for _, p in parts])
    blob = base64.b64encode(flat.tobytes()).decode()
    offs, o = {}, 0
    for name, p in parts:
        offs[name] = (o, p.size)
        o += p.size

    toks = GT["toks"][ids].astype(int)
    tok_rows = ",\n        ".join(
        "[" + ", ".join(str(v) for v in row) + "]" for row in toks)

    def intlist(xs):
        return "[" + ", ".join(str(int(x)) for x in xs) + "]"

    off_lines = "\n".join(
        f"    static let {n}Range = ({s}, {c})" for n, (s, c) in offs.items())

    with open(os.path.join(APP, "SKGeneWeights.swift"), "w") as f:
        f.write(f'''// GENERATED by nn/sk-gene/emit_swift.py — DO NOT EDIT.
// The grounded SK gene machine's frozen weights + curated gene set.
// Provenance: nn/sk-gene/ (ground_weights, weights, gene_table);
// laws: spec/neural/SKGeneCalculus.hs, SKGeneSemantics.hs,
// OctaveCodec.hs; design docs/sk-gene-calculus-2026-08-11.md.
// Weights ship as ONE base64 Float32-LE blob (large array literals
// stall the Swift type-checker); ranges are (offset, count).

import Foundation

enum SKGeneWeights {{
    static let d = {D}, eHid = 96, pHid = 48, featDim = 27, steps = {T}

{off_lines}

    static let geneCount = {len(ids)}
    static let geneID: [Int32] = {intlist(ids)}
    static let genePhase: [Int32] = {intlist(phases)}   // 0 order 1 boundary 2 chaos
    static let geneHalt: [Int32] = {intlist(halts)}
    static let geneNF: [Int32] = {intlist(nfs)}
    static let attractorNF: [Int32] = {intlist(att_nf)}

    static let geneToks: [[Int32]] = [
        {tok_rows}
    ]

    static let all: [Float] = {{
        let data = Data(base64Encoded: blobB64)!
        return data.withUnsafeBytes {{ raw in
            Array(raw.bindMemory(to: Float32.self))
        }}
    }}()

    static func slice(_ r: (Int, Int)) -> ArraySlice<Float> {{
        all[r.0 ..< r.0 + r.1]
    }}

    private static let blobB64 = "{blob}"
}}
''')

    # ── fixtures (float32, the parity law) ──────────────────────────
    rng = np.random.default_rng(7)
    blockA = rng.normal(0.4, 0.1, (8, 3)).astype(np.float32)
    blockB = rng.normal(0.5, 0.05, (8, 3)).astype(np.float32)

    H8 = np.zeros((8, 8), np.float32)
    for w in range(8):
        for e in range(8):
            H8[w, e] = (-1) ** bin(w & e).count("1") / 8.0

    def enc32(block, lev):
        coef = (H8 @ block).reshape(24)
        oh = np.zeros(3, np.float32); oh[lev] = 1
        x = np.concatenate([coef, oh]).astype(np.float32)
        x = (x - GW["fmean"]) / GW["fstd"]
        h = np.maximum(x @ GW["w1"] + GW["b1"], 0).astype(np.float32)
        h = np.maximum(h @ GW["w2"] + GW["b2"], 0).astype(np.float32)
        return (h @ GW["w3"] + GW["b3"]).astype(np.float32)

    def pred32(z, tok):
        x = np.concatenate([z, PW["tok"][tok]]).astype(np.float32)
        h = np.maximum(x @ PW["pw1"] + PW["pb1"], 0).astype(np.float32)
        return (z + h @ PW["pw2"] + PW["pb2"]).astype(np.float32)

    zA = enc32(blockA, 2)
    zB = enc32(blockB, 0)
    zS = pred32(zA, 0)
    zK = pred32(zA, 1)
    g0 = 0                                  # first curated gene
    z = GT["z0"][ids[g0]].astype(np.float32)
    for t in range(T):
        if GT["act"][ids[g0]][t] > 0:
            z = pred32(z, int(GT["toks"][ids[g0]][t]))
    roll = z

    def flist(a):
        return "[" + ", ".join(f"{v:.8e}" for v in np.ravel(a)) + "]"

    with open(os.path.join(TESTS, "SKGeneFixtures.swift"), "w") as f:
        f.write(f'''// GENERATED by nn/sk-gene/emit_swift.py — DO NOT EDIT.
// Float32 parity fixtures: the Swift port must reproduce these
// (computed from the identical frozen weights in numpy float32).

enum SKGeneFixtures {{
    static let blockA: [Float] = {flist(blockA)}   // 8 leaves × lab
    static let blockB: [Float] = {flist(blockB)}
    static let encALevel2: [Float] = {flist(zA)}
    static let encBLevel0: [Float] = {flist(zB)}
    static let predAS: [Float] = {flist(zS)}
    static let predAK: [Float] = {flist(zK)}
    static let gene0Rollout: [Float] = {flist(roll)}
}}
''')

    print(f"SKGeneWeights.swift: {len(flat)} floats "
          f"({len(blob)//1024} KB blob), {len(ids)} genes "
          f"({phases.count(0)}/{phases.count(1)}/{phases.count(2)} "
          f"order/boundary/chaos), {len(att_nf)} attractors")
    print("SKGeneFixtures.swift: enc×2, pred×2, rollout×1")


if __name__ == "__main__":
    main()
