#!/usr/bin/env python3
"""Generate DebayerWeights.h (baked constant arrays, FP32 + FP16) and golden.bin
from ../debayer/{weights.npz, weights_fp16.npz, golden.npz}.

Weight layout is MLX (O, kH, kW, I), flattened row-major, so the flat index is
((o*3 + ky)*3 + kx)*I + i  -- exactly what DebayerNet.metal indexes.
"""
import os
import struct

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "debayer")


def fmt(v):
    """Round-trip-exact float32 literal."""
    return repr(float(np.float32(v))) + "f"


def emit_array(lines, ctype, name, arr):
    flat = arr.astype(np.float32).reshape(-1)
    lines.append(f"constant {ctype} {name}[{flat.size}] = {{")
    for i in range(0, flat.size, 8):
        chunk = ", ".join(fmt(v) for v in flat[i:i + 8])
        lines.append("    " + chunk + ",")
    lines[-1] = lines[-1].rstrip(",")
    lines.append("};")
    lines.append("")


def main():
    w32 = np.load(os.path.join(SRC, "weights.npz"))
    w16 = np.load(os.path.join(SRC, "weights_fp16.npz"))

    lines = [
        "// GENERATED by gen_weights.py -- do not edit.",
        "// Source: nn/debayer/weights.npz + weights_fp16.npz (MLX (O,kH,kW,I) layout).",
        "#pragma once",
        "",
    ]
    total = 0
    for key in ("c1", "c2", "c3", "c4"):
        a32 = w32[key]
        a16 = w16[key]
        assert a32.shape == a16.shape and a32.shape[1:3] == (3, 3)
        total += a32.size
        emit_array(lines, "float", f"{key.upper()}_F32", a32)
        # fp16 values are exactly representable; float literals convert exactly to half
        emit_array(lines, "half", f"{key.upper()}_F16", a16.astype(np.float32))
    assert total == 5616, total
    with open(os.path.join(HERE, "DebayerWeights.h"), "w") as f:
        f.write("\n".join(lines))
    print(f"DebayerWeights.h: {total} params x2 precisions")

    g = np.load(os.path.join(SRC, "golden.npz"))
    names = [str(n) for n in g["names"]]
    mosaics = g["mosaics"].astype(np.float32)
    outputs = g["outputs"].astype(np.float32)
    with open(os.path.join(HERE, "golden.bin"), "wb") as f:
        f.write(struct.pack("<I", len(names)))
        for i, name in enumerate(names):
            nb = name.encode()
            h, w = mosaics[i].shape
            f.write(struct.pack("<I", len(nb)) + nb)
            f.write(struct.pack("<II", h, w))
            f.write(mosaics[i].tobytes())
            f.write(outputs[i].tobytes())
    print(f"golden.bin: {len(names)} cases {names}")


if __name__ == "__main__":
    main()
