-- ════════════════════════════════════════════════════════════════
-- ColourLatent: the space the model is a map OF
--
-- ★ Daniel, 2026-08-14: "The model we train MUST be wise in the
-- 64x64x64 GIF creation, because 256 colour every 64 frames is
-- something that CAN be explored in latent colour space."
--
-- THE CLAIM THIS FILE MAKES, AND IT IS A FACT ABOUT THE SHIPPED APP
-- RATHER THAN A PROPOSAL: that latent space already exists, it is
-- already exact, and every GIF the app has ever exported already
-- carries its own coordinates. A Tesseract GIF's colour is 64 frames
-- of 256 entries = 49152 bytes, and all of it is generated by 16
-- fields per frame -- 13 from DYAD STATS v3 plus 3 from DYAD
-- GROUNDHUE v2 -- of which TWO ARE BOOLS, so 14 numbers and 2 bits
-- per frame: 896 numbers and 128 bits for the whole GIF, by a
-- decoder that is already shipped and already gated byte-for-byte
-- (GIFMachine.rebuildTables). 54.86 : 1, exact.
--
-- So nothing needs to LEARN a colour space. What is missing is a
-- METRIC on one that is already there — which regions of those 896
-- numbers a person can tell apart. That is a far smaller and far
-- better-posed problem than "train a model on GIFs", and it is the
-- difference between something that could invent an unlawful
-- artifact and something that structurally cannot.
--
-- ★ AND IT MAY NEED NO WEIGHTS. CL6 shows the metric cannot be a
-- diagonal, not that it must be learned; the pullback J^T J through
-- the continuous table is arithmetic. An earlier draft of this file
-- concluded "has to be LEARNED" without checking that, and the
-- correction is recorded rather than quietly applied.
--
-- ★ WHAT THIS FILE DOES NOT YET DESCRIBE, stated up front so the
-- coverage is not overread:
--
--   THE TEMPORAL AXIS. Every law here is about ONE frame's generator.
--     The artifact is a TRAJECTORY of 64 of them, and how consecutive
--     ticks may relate is unstated. WeaveState owns a 33-number
--     causal state per frame; the map between that and this
--     generator is not written anywhere.
--   THE DECODER IS A STAND-IN (§ 2). Structurally faithful, but not
--     PairTree's arithmetic. CL2, CL3 and CL8 are therefore proved
--     about a MODEL of the decoder. Proving them about the shipped
--     one means a Swift port gated against DyadPalette.
--   DEPTH. The role split decides which half of the table a pixel can
--     land in, so the REACHABLE region of this space depends on the
--     depth field. Nothing here says how.
--   THE BALANCED BIT. One discrete coordinate per frame that no
--     metric can interpolate through (CL1). A sampler must enumerate
--     it; a metric learner must be told it is not a direction.
--
-- ── SCOPE, per the lesson in docs/session-2026-08-14-tensor.md §5 ─
--
-- Grepped before writing. These specs own the ground this one stands
-- on and it cites rather than restates them:
--
--   spec/quantization/DyadPalette.hs  DY*   what the 13 numbers ARE
--     and how a table is generated from them.
--   spec/quantization/PairTree.hs     PT*   the analytic tree: the
--     table is a pure function of the traced stats (PT7-PT9).
--   spec/neural/WeaveState.hs         WS*   the causal 33-number
--     state, and that 256! relabelings are free in energy AND in LZW.
--   spec/output/AdditiveLadder.hs     AD*   the index's strata, which
--     are the latent's levels — not a modelling choice.
--   spec/statistics/TilingEntropy.hs  TE*   E in bits.
--   spec/neural/JepaH.hs              JH*   the model's own laws.
--
-- What is NOT owned anywhere, and is this file's whole content: the
-- latent's DIMENSION, its EXACTNESS, the group it must be a quotient
-- by, and the fact that its natural metric is not the Euclidean one.
-- ════════════════════════════════════════════════════════════════

module ColourLatent where

import Data.Bits (xor)
import Data.List (nub, sort)

-- ════════════════════════════════════════════════════════════════
-- § 1. THE DIMENSION
-- ════════════════════════════════════════════════════════════════

-- | The generating numbers of ONE frame's palette. THIRTEEN come from
--   DYAD STATS v3 (the OKLab centroid, the upper triangle of its
--   covariance, the three ground moments, the cap) and THREE more
--   from DYAD GROUNDHUE v2, which GIFMachine writes on EVERY export
--   unconditionally: the ground rotation as a direction (a, b -- GH5
--   says a direction, never an angle) and the balanced flag.
--
--   ★ COUNTING ONLY THE STATS IS AN UNDERCOUNT, and it is recorded
--   here because the first draft of this file made it. A rebuild that
--   ignores the GROUNDHUE section reconstructs `balanced` as false and
--   regenerates the v7 table -- a silent provenance break, which is
--   exactly what one earlier change shipped (GIFMachine's own comment
--   says so). The generator is 16 fields, and a latent that models 13
--   of them cannot reach every lawful GIF.
--
--   Named rather than indexed, because a latent whose axes have no
--   names cannot be steered.
data FrameLatent = FrameLatent
  { muL, muA, muB     :: Double     -- 3  the centroid
  , cLL, cLA, cLB     :: Double     -- 6  the covariance, upper triangle
  , cAA, cAB, cBB     :: Double
  , betaC, alphaC, dL :: Double     -- 3  the ground family's moments
  , capped            :: Bool       -- 1  the dictionary prior's cap (a BIT)
  , rotA, rotB        :: Double     -- 2  GROUNDHUE v2: the direction
  , balanced          :: Bool       -- 1  GROUNDHUE v2: the flag (a BIT)
  } deriving (Eq, Show)

-- | Continuous coordinates a metric can move through.
frameDims :: Int
frameDims = 14

-- | The DISCRETE coordinates. Both are Bools in the shipped code
--   (`DyadPalette.GroundMoments.capped` and `.balanced`) that the
--   trace writes as "1"/"0" and the rebuild parses back to Bool, so
--   a reader counting fields in the trace line miscounts them as
--   continuous. They are not directions: a metric learner cannot
--   interpolate through them and a sampler must ENUMERATE them.
frameBits :: Int
frameBits = 2

statsDims :: Int
statsDims = 13                                 -- the DYAD STATS v3 half

frames :: Int
frames = 64

paletteEntries :: Int
paletteEntries = 256

paletteBytesPerFrame :: Int
paletteBytesPerFrame = paletteEntries * 3      -- one Local Color Table

-- | The whole colour content of one GIF.
latentDims :: Int
latentDims = frames * frameDims                -- 896

latentBits :: Int
latentBits = frames * frameBits                -- 128

colourBytes :: Int
colourBytes = frames * paletteBytesPerFrame    -- 49152

toList :: FrameLatent -> [Double]
toList f = [ muL f, muA f, muB f
           , cLL f, cLA f, cLB f, cAA f, cAB f, cBB f
           , betaC f, alphaC f, dL f
           , rotA f, rotB f ]

-- ════════════════════════════════════════════════════════════════
-- § 2. THE DECODER IS THE LAW
-- ════════════════════════════════════════════════════════════════
--
-- A stand-in with the SHIPPED decoder's STRUCTURE, not its
-- arithmetic: DyadPalette.hs and PairTree.hs own the arithmetic and
-- this file must not fork it. What is modelled here is the only
-- structure the latent's laws depend on:
--
--   1. the figure half is generated by a deterministic split of the
--      centroid and covariance (PT7-PT9: analytic, basis never
--      rotates), so 128 entries come out of 9 numbers;
--   2. the ground half is the sigma-mirror, T[255-i] = ground(T[i]),
--      generated from the 3 moments and the cap;
--   3. therefore the map latent -> table is TOTAL. Every point in the
--      space decodes. The model cannot produce an illegal artifact
--      even in principle, because the decoder IS the law.

type Entry = (Double, Double, Double)

-- | The leading eigenpair of the 3x3 covariance, by deterministic
--   power iteration. This is what makes the OFF-DIAGONAL covariance
--   coordinates load-bearing: PT7-PT9's analytic split takes the
--   child mean to mu +/- sqrt(lambda)*sqrt(2/pi) along the split
--   AXIS, and that axis is the leading eigenvector, which cLA, cLB
--   and cAB determine. An earlier draft of this file split on the
--   diagonal alone, which left six of the fourteen coordinates
--   unread and three axioms vacuous in them.
leadingEigen :: FrameLatent -> ((Double, Double, Double), Double)
leadingEigen f = go 40 (0.577, 0.577, 0.578)
  where
    mul (x, y, z) =
      ( cLL f * x + cLA f * y + cLB f * z
      , cLA f * x + cAA f * y + cAB f * z
      , cLB f * x + cAB f * y + cBB f * z )
    norm (x, y, z) = sqrt (x*x + y*y + z*z)
    go :: Int -> (Double, Double, Double) -> ((Double, Double, Double), Double)
    go 0 v = (v, ray v)
    go n v =
      let w = mul v
          m = norm w
      in if m < 1e-15 then (v, 0) else go (n - 1 :: Int) (scale (1 / m) w)
    scale k (x, y, z) = (k * x, k * y, k * z)
    ray v@(x, y, z) = let (a, b, c) = mul v in a * x + b * y + c * z

-- | The figure half: 128 entries from the centroid, the full
--   covariance and the tree's bit-triples. Bit 0 takes the analytic
--   half-normal step along the leading axis; bits 1..3 spread on the
--   coordinate axes, which is PT's "basis never rotates" read
--   literally. Structure only -- DyadPalette.hs and PairTree.hs own
--   the arithmetic and this file must not fork it.
figureHalf :: FrameLatent -> [Entry]
figureHalf f =
  [ ( muL f + sgn 0 j * step * ux + sgn 1 j * 0.5 * sqrt (max 0 (cLL f))
    , muA f + sgn 0 j * step * uy + sgn 2 j * 0.5 * sqrt (max 0 (cAA f))
    , muB f + sgn 0 j * step * uz + sgn 3 j * 0.5 * sqrt (max 0 (cBB f)) )
  | j <- [0 .. 127] ]
  where
    ((ux, uy, uz), lam) = leadingEigen f
    step = sqrt (max 0 lam) * sqrt (2 / pi)      -- the half-normal moment
    sgn b j = fromIntegral (1 - 2 * ((j `div` (2 ^ (b :: Int))) `mod` 2)) :: Double

-- | The ground half: the sigma-mirror's generator. Reads the three
--   moments, BOTH bits, and the hue direction, so no declared
--   coordinate is inert.
--
--   `capped` is the dictionary prior's role law (DyadPalette.swift:412
--   `gm.capped ? min(c, cRaw) : cRaw`) -- a BIT, not a magnitude.
--   `balanced` is WhiteBalance's v2 flag, which splits the rigid
--   L-shift instead of loading it all on the ground.
--   (rotA, rotB) is GroundHue's rotation as a DIRECTION, never an
--   angle (GH5), so it is normalised here and applied as a planar
--   rotation of the chroma pair.
groundOf :: FrameLatent -> Entry -> Entry
groundOf f (l, a, b) = (l + shift, a2 * k, b2 * k)
  where
    shift = if balanced f then dL f / 2 else dL f
    chroma = sqrt (a * a + b * b)
    p = betaC f ** min 4 (max 0 (alphaC f))
    raw = chroma * p
    c = if capped f then min chroma raw else raw    -- the cap is a GATE
    k = if chroma < 1e-12 then 0 else c / chroma
    m = sqrt (rotA f * rotA f + rotB f * rotB f)
    (ra, rb) = if m < 1e-12 then (1, 0) else (rotA f / m, rotB f / m)
    a2 = a * ra - b * rb
    b2 = a * rb + b * ra

-- | The full 256-entry table: DY2's form, sigma-mirrored.
decode :: FrameLatent -> [Entry]
decode f = fig ++ map (groundOf f) (reverse fig)
  where fig = figureHalf f

-- ════════════════════════════════════════════════════════════════
-- § 3. THE QUOTIENT THE MODEL MUST RESPECT
-- ════════════════════════════════════════════════════════════════
--
-- WS says 256! relabelings are free in energy and in LZW bits. They
-- are NOT all available here: the DYAD involution sigma(i) = 255 - i
-- is decreed, so a lawful relabeling must COMMUTE with it. The
-- XOR-by-mask permutations do, exactly, because on 8 bits
-- sigma(i) = i `xor` 255 and xor is commutative and associative.
--
-- That gives a group of order 256 acting freely on the table, under
-- which the SET of colours -- and therefore E, the occupancy census
-- and the LZW bill -- are invariant. A model trained without this
-- invariance learns index labels instead of colour, which is the
-- memorisation failure JepaH's v7 hypernet was built to make
-- structurally impossible. Here it is stated as a law rather than
-- left to an architecture to imply.

sigmaIdx :: Int -> Int
sigmaIdx i = i `xor` 255

relabel :: Int -> Int -> Int
relabel mask i = i `xor` mask

-- ════════════════════════════════════════════════════════════════
-- § 4. THE METRIC IS NOT THE EUCLIDEAN ONE
-- ════════════════════════════════════════════════════════════════
--
-- The 13 numbers are not commensurable: three are means (linear in
-- colour), six are covariances (QUADRATIC), three are ratios and one
-- is a cap. Moving one unit along a mean and one unit along a
-- variance do not move the picture by the same amount, and no
-- reweighting fixes it, because the ratio depends on where you are.
--
-- So the metric the model must supply is the PULLBACK of colour
-- distance through the decoder. That is the whole content of "steps
-- a person can see rather than steps that are numerically uniform"
-- (docs/model-placement.md § 4.1's CHOICE), stated as geometry.

dist :: Entry -> Entry -> Double
dist (a, b, c) (x, y, z) =
  sqrt ((a - x) ^ (2 :: Int) + (b - y) ^ (2 :: Int) + (c - z) ^ (2 :: Int))

decodedDistance :: FrameLatent -> FrameLatent -> Double
decodedDistance p q = sum (zipWith dist (decode p) (decode q))
                    / fromIntegral paletteEntries

latentDistance :: FrameLatent -> FrameLatent -> Double
latentDistance p q =
  sqrt (sum [ (a - b) ^ (2 :: Int) | (a, b) <- zip (toList p) (toList q) ])

-- ════════════════════════════════════════════════════════════════
-- § 5. THE AXIOMS
-- ════════════════════════════════════════════════════════════════

eps :: Double
eps = 1e-12

base :: FrameLatent
base = FrameLatent
  { muL = 0.62, muA = 0.05, muB = 0.11
  , cLL = 0.0090, cLA = 0.0011, cLB = 0.0007
  , cAA = 0.0040, cAB = 0.0003, cBB = 0.0025
  , betaC = 0.83, alphaC = 1.15, dL = -0.09, capped = False
  , rotA = 0.94, rotB = 0.34, balanced = False }

-- (CL1) ★ THE DIMENSION, AND THE RATIO. 832 numbers generate 49152
--       palette bytes: the colour of a whole GIF is a point in a
--       space 59 times smaller than the bytes it writes, and the map
--       is EXACT, not an approximation. This is why the space can be
--       explored at all.
axiom_CL1 :: Bool
axiom_CL1 =
     latentDims == 896
  && latentBits == 128
  && colourBytes == 49152
  && frameDims == 14
  && frameBits == 2
  && statsDims == 13
  && length (toList base) == frameDims
  -- ★ THE ARITY, CORRECTED TWICE. 13 stats fields + 3 groundhue
  -- fields = 16, but TWO of the sixteen are Bools, so the space a
  -- metric moves through is 14-dimensional per frame, not 16 and
  -- not 15. Counting fields in the trace line is what gets this
  -- wrong, because both bits are written there as "1"/"0".
  && statsDims + 3 == frameDims + frameBits
  && colourBytes * 100 `div` latentDims == 5485   -- 54.86 : 1
  && length (decode base) == paletteEntries

-- (CL2) THE DECODER IS TOTAL. Every point decodes to a full table,
--       including degenerate ones — a zero covariance, a flat cap, a
--       negative lightness shift. The model therefore cannot reach an
--       illegal artifact, because there is no illegal point to reach.
axiom_CL2 :: Bool
axiom_CL2 =
  all (\f -> length (decode f) == paletteEntries
             && all finite (concatMap triple (decode f)))
      [ base
      , base { cLL = 0, cAA = 0, cBB = 0, cLA = 0, cLB = 0, cAB = 0 }
      , base { betaC = 0, alphaC = 0 }
      , base { dL = -10, capped = True }
      , base { muL = 0, muA = 0, muB = 0 }
      , base { rotA = 0, rotB = 0 }               -- a degenerate direction
      , base { balanced = True }
      , base { cLA = 9, cLB = -9, cAB = 9 } ]     -- not positive definite
  where
    triple (a, b, c) = [a, b, c]
    finite x = not (isNaN x) && not (isInfinite x)

-- (CL3) ★ THE SIGMA FORM SURVIVES DECODE. The ground half is the
--       mirror of the figure half, entry by entry: T[255-i] is the
--       ground of T[i]. The latent cannot express a table that
--       violates the decreed involution, which is the strongest
--       statement available about what a trained model may do.
axiom_CL3 :: Bool
axiom_CL3 =
  and [ decode base !! (255 - i) == groundOf base (decode base !! i)
      | i <- [0 .. 127] ]

-- (CL4) ★ THE RELABELING GROUP COMMUTES WITH SIGMA, and has order
--       256. These are the moves that cost nothing (WS), so they are
--       exactly the moves the latent must be a quotient BY. A model
--       that distinguishes them is reading labels, not colour.
axiom_CL4 :: Bool
axiom_CL4 =
     and [ relabel m (sigmaIdx i) == sigmaIdx (relabel m i)
         | m <- [0 .. 255], i <- [0 .. 255] ]
  && length (nub [ [ relabel m i | i <- [0 .. 255] ] | m <- [0 .. 255] ]) == 256
  && and [ sort (map (relabel m) [0 .. 255]) == [0 .. 255] | m <- [0 .. 255] ]

-- (CL5) A RELABELING MOVES NO COLOUR. The multiset of table entries
--       is invariant, so E, the occupancy census and the LZW bill are
--       too — which is what "free" meant in WS, checked here on the
--       table itself rather than on the energy alone.
axiom_CL5 :: Bool
axiom_CL5 =
  and [ sortEntries (permuteBy m tbl) == sortEntries tbl | m <- [0 .. 255] ]
  where
    tbl = decode base
    permuteBy m t = [ t !! relabel m i | i <- [0 .. 255] ]
    sortEntries = sort . map (\(a, b, c) -> (round' a, round' b, round' c))
    round' x = fromIntegral (round (x * 1e9) :: Integer) / 1e9 :: Double

-- (CL6) ★ EUCLIDEAN DISTANCE IN THE LATENT IS NOT COLOUR DISTANCE,
--       AND NO FIXED REWEIGHTING CAN MAKE IT ONE. Two moves of the
--       same latent length move the picture by different amounts;
--       that alone would be fixable by weighting the axes. The fact
--       that is NOT fixable, and the one checked here, is that the
--       ratio between them is STRICTLY DECREASING in the covariance
--       and CROSSES ONE. At a tight covariance a variance step moves
--       the picture further than a mean step; at a wide one it moves
--       it less. Their ORDER REVERSES, so no positive constant weight
--       makes them commensurable anywhere except on the crossing.
--
--       Stated with no threshold and no tuned number: monotone, and
--       (ratio - 1) changes sign. The metric therefore has to be a
--       FIELD over the space, not a diagonal. Whether learning it
--       needs WEIGHTS is a separate question this file does not
--       answer: the pullback g = J^T J through the continuous table
--       is arithmetic, and an earlier draft of this axiom concluded
--       "has to be LEARNED" without checking that.
axiom_CL6 :: Bool
axiom_CL6 =
     abs (latentDistance base tight - latentDistance base wide) < 1e-9
  && strictlyDecreasing ratios
  && head ratios > 1 && last ratios < 1
  where
    step = 0.02
    tight = base { muL = muL base + step }
    wide  = base { cLL = cLL base + step }
    ratios = map ratioAt [0.25, 1, 2, 4, 10, 40]
    ratioAt k =
      let here = base { cLL = cLL base * k }
          dm = decodedDistance here (here { muL = muL here + step })
          dv = decodedDistance here (here { cLL = cLL here + step })
      in dv / dm
    strictlyDecreasing xs = and (zipWith (>) xs (drop 1 xs))

-- (CL7) THE LEVELS ARE THE ARTIFACT'S, NOT THE MODEL'S. AdditiveLadder
--       already proved the index is three strata, so a hierarchical
--       latent has its depth FORCED at three and its widths forced at
--       the strata's own level counts. Nothing here is a
--       hyperparameter.
axiom_CL7 :: Bool
axiom_CL7 =
     levels == [4, 32, 256]
  && product [4, 8, 8] == 256
  && length levels == 3
  where levels = [4, 32, 256]     -- AD: r16 4-level, r32 32-level, r64 leaf

-- (CL8) ★ EVERY CORPUS POINT IS A LAWFUL GIF BY CONSTRUCTION. A
--       sampler that draws in this space and decodes through the
--       shipped law needs no photograph, which is what
--       NO-CAPTURE-TRAINING demanded, and cannot emit an unlawful
--       artifact, which is what the model-placement ruling demanded.
--       Both decrees are satisfied by the SHAPE of the corpus rather
--       than by anyone's discipline.
axiom_CL8 :: Bool
axiom_CL8 =
  all lawful [ base { muL = 0.2 + 0.1 * fromIntegral k
                    , cLL = 0.001 * fromIntegral k
                    , betaC = 0.5 + 0.05 * fromIntegral k }
             | k <- [0 .. 12 :: Int] ]
  where
    lawful f =
      let t = decode f
      in length t == paletteEntries
         && and [ t !! (255 - i) == groundOf f (t !! i) | i <- [0 .. 127] ]

-- ════════════════════════════════════════════════════════════════
-- § 6. THE HARNESS
-- ════════════════════════════════════════════════════════════════

check :: String -> [Bool] -> IO Bool
check name bs = do
  let ok = and bs
  putStrLn $ "  " ++ (if ok then "\10003" else "\10007") ++ " " ++ name
  return ok

main :: IO ()
main = do
  putStrLn "══════════════════════════════════════════════════════════"
  putStrLn " ColourLatent: the space the model is a map OF"
  putStrLn "══════════════════════════════════════════════════════════"
  putStrLn ""
  putStrLn "  a GIF's whole colour content:"
  putStrLn $ "    written        " ++ show colourBytes
             ++ " B  (64 frames x 256 entries x 3)"
  putStrLn $ "    generated by   " ++ show latentDims
             ++ " numbers + " ++ show latentBits
             ++ " bits (64 frames x 14 + 2)"
  putStrLn $ "    ratio          54.86 : 1, EXACT"
  putStrLn ""
  rs <- sequence
    [ check "CL1  * 896 numbers + 128 bits generate 49152 B"     [axiom_CL1]
    , check "CL2  the decoder is TOTAL: no illegal point exists" [axiom_CL2]
    , check "CL3  * the sigma form survives decode, entry by entry" [axiom_CL3]
    , check "CL4  * the relabeling group commutes with sigma, |G|=256" [axiom_CL4]
    , check "CL5  a relabeling moves no colour: E and LZW invariant" [axiom_CL5]
    , check "CL6  * the metric ratio reverses ORDER: no diagonal" [axiom_CL6]
    , check "CL7  the levels are the artifact's, not the model's" [axiom_CL7]
    , check "CL8  * every corpus point is a lawful GIF by construction" [axiom_CL8]
    ]
  putStrLn ""
  putStrLn "  WHAT THE MODEL IS FOR, stated as geometry:"
  putStrLn "    the space          exists, and is exact (CL1)"
  putStrLn "    the decoder        is the shipped law (CL2, CL3)"
  putStrLn "    the symmetry       must be quotiented out (CL4, CL5)"
  putStrLn "    the METRIC         missing, and it is a FIELD not a"
  putStrLn "                       diagonal: the ratio REVERSES (CL6)"
  putStrLn ""
  putStrLn "  So if a run is needed at all it is a METRIC run, never"
  putStrLn "  a generator: the generator already ships. Whether the"
  putStrLn "  metric needs WEIGHTS is open -- the pullback J^T J"
  putStrLn "  through the continuous table is arithmetic."
  putStrLn ""
  if and rs
    then putStrLn "  all axioms hold"
    else error "ColourLatent: axioms failed"
