// SKGeneTests — the CPU twin is the law.
//
// Parity fixtures (SKGeneFixtures.swift) are generated by
// nn/sk-gene/emit_swift.py in numpy float32 from the IDENTICAL
// frozen weights; the Swift port must reproduce them. Pure logic —
// runs on the simulator (house rule: camera code compile-only,
// logic suites sim-runnable).

import XCTest
@testable import Tesseract

final class SKGeneTests: XCTestCase {

    private func assertClose(_ got: [Float], _ want: [Float],
                             tol: Float, _ label: String) {
        XCTAssertEqual(got.count, want.count, label)
        for (g, w) in zip(got, want) {
            XCTAssertEqual(g, w, accuracy: tol, label)
        }
    }

    private func blocks(_ flat: [Float]) -> [(Float, Float, Float)] {
        (0 ..< 8).map { (flat[3 * $0], flat[3 * $0 + 1], flat[3 * $0 + 2]) }
    }

    /// E parity: Haar features + standardization + MLP, both levels.
    func testEncoderParity() {
        assertClose(SKGene.encode(block: blocks(SKGeneFixtures.blockA),
                                  level: 2),
                    SKGeneFixtures.encALevel2, tol: 5e-4, "enc A lev2")
        assertClose(SKGene.encode(block: blocks(SKGeneFixtures.blockB),
                                  level: 0),
                    SKGeneFixtures.encBLevel0, tol: 5e-4, "enc B lev0")
    }

    /// Predictor parity: one S step and one K step from enc(A).
    func testPredictorParity() {
        let z = SKGeneFixtures.encALevel2
        assertClose(SKGene.predict(z, tokIsK: false),
                    SKGeneFixtures.predAS, tol: 5e-4, "pred S")
        assertClose(SKGene.predict(z, tokIsK: true),
                    SKGeneFixtures.predAK, tol: 5e-4, "pred K")
    }

    /// Full activation of the first curated gene from its own z0.
    func testGeneRolloutParity() {
        assertClose(SKGene.activate(gene: 0),
                    SKGeneFixtures.gene0Rollout, tol: 2e-3, "rollout")
    }

    /// The curated table's structure: 64/32/2 phase split, act masks
    /// monotone (once idle, stays idle — the SK9 lane law), halted
    /// genes' active step count equals their halting time.
    func testCuratedTableStructure() {
        let W = SKGeneWeights.self
        XCTAssertEqual(W.geneCount, 98)
        let phases = (0 ..< 3).map { p in
            W.genePhase.filter { $0 == Int32(p) }.count
        }
        XCTAssertEqual(phases, [64, 32, 2])
        let act = Array(W.slice(W.geneActRange))
        for g in 0 ..< W.geneCount {
            var seenIdle = false
            var active = 0
            for t in 0 ..< W.steps {
                let on = act[g * W.steps + t] > 0
                if on {
                    XCTAssertFalse(seenIdle, "act mask must be monotone")
                    active += 1
                } else {
                    seenIdle = true
                }
            }
            let halt = Int(W.geneHalt[g])
            if halt >= 0 {
                XCTAssertEqual(active, halt, "active steps == halting time")
            } else {
                XCTAssertEqual(active, W.steps, "divergers run all steps")
            }
        }
    }

    /// Attractor table aligned; ORDER genes' rollouts reproduce the
    /// float32 law's 96-way attractor decisions EXACTLY. The pinned
    /// 55/64 is the reference computed in numpy float32 from the
    /// identical weights (the harder 96-way argmin, not P4's binary
    /// contrast — parity, not aspiration).
    func testOrderGenesMatchTheLawsAttractorDecisions() {
        let W = SKGeneWeights.self
        XCTAssertEqual(W.attractorNF.count * 24,
                       W.attractorsRange.1)
        var hits = 0, total = 0
        for g in 0 ..< W.geneCount where W.genePhase[g] == 0 {
            let final = SKGene.activate(gene: g)
            if SKGene.nearestAttractor(final).nf == W.geneNF[g] { hits += 1 }
            total += 1
        }
        XCTAssertEqual(total, 64)
        XCTAssertEqual(hits, 55, "law parity: float32 reference gives 55/64")
    }
}
