// SKGene.swift — the grounded SK gene machine, Swift port.
//
// Placement ruling (Daniel, 2026-08-11): "if the CORE AI can be
// placed and used in the app do that." Design and laws:
// docs/sk-gene-calculus-2026-08-11.md (§5 activation, §12 gauge,
// §14 grounding); Haskell authority spec/neural/{SKGeneCalculus,
// SKGeneSemantics, OctaveCodec}.hs; weights + curated gene set in
// SKGeneWeights.swift (generated by nn/sk-gene/emit_swift.py).
//
// Three CPU maps — the law, gated by SKGeneTests fixtures against
// the Mac float32 reference:
//   encode   E: 2×2×2 OKLab block (wiring order t,y,x → Haar
//            characters) + octave level → z ∈ ℝ²⁴, the gene space
//   predict  one passer step z' = z + MLP([z ; tok]), tok ∈ {S, K}
//   activate play a curated gene's 16-step schedule (halted lanes
//            idle by the act mask — lane-uniform, spec SK9)
//
// The fused ANE graphs (SKGenePasserModel / SKGeneCodecModel,
// Tesseract/ML/) are bundled for the one-dispatch path; loaders
// below prove availability. v1 runtime use is MEASUREMENT ONLY:
// GIFMachine appends an "SK GENES v1" provenance line when
// CameraConfig.skGenes is enabled — no GIF pixel byte depends on
// any of this (TriScaleLadder / Dissonance precedent).

import Foundation
import CoreML

enum SKGene {

    // MARK: - Weights (sliced once from the generated blob)

    private static let W = SKGeneWeights.self
    private static let gW1 = Array(W.slice(W.gW1Range))
    private static let gB1 = Array(W.slice(W.gB1Range))
    private static let gW2 = Array(W.slice(W.gW2Range))
    private static let gB2 = Array(W.slice(W.gB2Range))
    private static let gW3 = Array(W.slice(W.gW3Range))
    private static let gB3 = Array(W.slice(W.gB3Range))
    private static let fMean = Array(W.slice(W.fMeanRange))
    private static let fStd = Array(W.slice(W.fStdRange))
    private static let pW1 = Array(W.slice(W.pW1Range))
    private static let pB1 = Array(W.slice(W.pB1Range))
    private static let pW2 = Array(W.slice(W.pW2Range))
    private static let pB2 = Array(W.slice(W.pB2Range))
    private static let tokS = Array(W.slice(W.tokSRange))
    private static let tokK = Array(W.slice(W.tokKRange))
    private static let attractors = Array(W.slice(W.attractorsRange))
    private static let geneZ0 = Array(W.slice(W.geneZ0Range))
    private static let geneAct = Array(W.slice(W.geneActRange))

    private static func matvec(_ m: [Float], _ x: [Float],
                               _ bias: [Float]) -> [Float] {
        let nOut = bias.count, nIn = x.count
        var out = bias
        for i in 0 ..< nIn {
            let xi = x[i]
            if xi == 0 { continue }
            let row = i * nOut
            for j in 0 ..< nOut { out[j] += xi * m[row + j] }
        }
        return out
    }

    private static func relu(_ x: [Float]) -> [Float] {
        x.map { max($0, 0) }
    }

    // MARK: - E: the grounding encoder (§14)

    /// Haar character coefficients of the block: leaf order
    /// ε = (t,y,x), idx = 4t + 2y + x — the wiring is the gauge.
    static func encode(block: [(Float, Float, Float)], level: Int)
        -> [Float] {
        precondition(block.count == 8 && (0...2).contains(level))
        var feat = [Float](repeating: 0, count: 27)
        for w in 0 ..< 8 {
            var l: Float = 0, a: Float = 0, b: Float = 0
            for e in 0 ..< 8 {
                let s: Float = (w & e).nonzeroBitCount % 2 == 0 ? 0.125 : -0.125
                l += s * block[e].0; a += s * block[e].1; b += s * block[e].2
            }
            feat[3 * w] = l; feat[3 * w + 1] = a; feat[3 * w + 2] = b
        }
        feat[24 + level] = 1
        for i in 0 ..< 27 { feat[i] = (feat[i] - fMean[i]) / fStd[i] }
        let h1 = relu(matvec(gW1, feat, gB1))
        let h2 = relu(matvec(gW2, h1, gB2))
        return matvec(gW3, h2, gB3)
    }

    // MARK: - The passer predictor (one reduction step)

    static func predict(_ z: [Float], tokIsK: Bool) -> [Float] {
        let x = z + (tokIsK ? tokK : tokS)
        let h = relu(matvec(pW1, x, pB1))
        let dz = matvec(pW2, h, pB2)
        return zip(z, dz).map(+)
    }

    /// Play curated gene g's schedule from a latent (the gene's own
    /// z0 when `from` is nil). Halted steps idle via the act mask.
    static func activate(gene g: Int, from z0: [Float]? = nil) -> [Float] {
        var z = z0 ?? Array(geneZ0[g * 24 ..< g * 24 + 24])
        for t in 0 ..< W.steps where geneAct[g * W.steps + t] > 0 {
            z = predict(z, tokIsK: W.geneToks[g][t] == 1)
        }
        return z
    }

    /// Nearest attractor on the unit sphere (the P4/F1 decision).
    static func nearestAttractor(_ z: [Float]) -> (nf: Int32, d2: Float) {
        let zn = normalized(z)
        var best: Int = 0
        var bestD = Float.greatestFiniteMagnitude
        let n = SKGeneWeights.attractorNF.count
        for i in 0 ..< n {
            let an = normalized(Array(attractors[i * 24 ..< i * 24 + 24]))
            var d: Float = 0
            for j in 0 ..< 24 { let t = zn[j] - an[j]; d += t * t }
            if d < bestD { bestD = d; best = i }
        }
        return (SKGeneWeights.attractorNF[best], bestD)
    }

    private static func normalized(_ z: [Float]) -> [Float] {
        var n: Float = 0
        for v in z { n += v * v }
        n = max(n.squareRoot(), 1e-8)
        return z.map { $0 / n }
    }

    // MARK: - Fused graphs (bundled; the one-dispatch path)

    // SKGeneGroundModel is THE CORE as a model: the grounding
    // encoder E, 512 blocks per dispatch. Its contract is the
    // DyadAssign lesson — inputs are PRE-STANDARDIZED float32
    // features (Haar characters + level, centered/scaled on CPU);
    // standardizing inside the fp16 graph amplifies rounding by
    // 1/σ and was measured at O(1) error before this contract.
    nonisolated(unsafe) private static let groundModel: MLModel? =
        loadModel("SKGeneGroundModel")
    nonisolated(unsafe) private static let passerModel: MLModel? =
        loadModel("SKGenePasserModel")
    nonisolated(unsafe) private static let codecModel: MLModel? =
        loadModel("SKGeneCodecModel")

    private static func loadModel(_ resource: String) -> MLModel? {
        guard let url = Bundle.main.url(forResource: resource,
                                        withExtension: "mlmodelc")
        else { return nil }
        let config = MLModelConfiguration()
        config.computeUnits = .all
        return try? MLModel(contentsOf: url, configuration: config)
    }

    static var isGroundAvailable: Bool { groundModel != nil }
    static var isPasserAvailable: Bool { passerModel != nil }
    static var isCodecAvailable: Bool { codecModel != nil }

    // MARK: - Telemetry (measurement only)

    /// The "SK GENES v1" provenance line: pool the capture cube to
    /// the rung-16 lattice (level 2 of the tower, TL9's judgment
    /// cadence), encode its 512 2×2×2 blocks, and play one gene per
    /// phase class from every block latent. Reported per class:
    /// the modal attractor, its hit fraction, and the mean latent
    /// displacement — CHAOS reports displacement only (no
    /// attractor; the orbit never lands). Comment bytes only.
    static func trace(sourceRGB: [[(Float, Float, Float)]],
                      side: Int) -> String? {
        let frames = sourceRGB.count
        guard frames >= 64, side >= 64 else { return nil }

        // 64³ OKLab → 16³ by 4³ mean pooling
        var cube = [Float](repeating: 0, count: 16 * 16 * 16 * 3)
        let inv = Float(1.0 / (4.0 * 4.0 * 4.0))
        for tc in 0 ..< 16 {
            for yc in 0 ..< 16 {
                for xc in 0 ..< 16 {
                    var l: Float = 0, a: Float = 0, b: Float = 0
                    for dt in 0 ..< 4 {
                        let src = sourceRGB[4 * tc + dt]
                        for dy in 0 ..< 4 {
                            let row = (4 * yc + dy) * side
                            for dx in 0 ..< 4 {
                                let p = src[row + 4 * xc + dx]
                                let lab = DyadPalette.oklab(
                                    fromSRGB8: PhaseTelemetry.srgb8(from: p))
                                l += Float(lab.l); a += Float(lab.a)
                                b += Float(lab.b)
                            }
                        }
                    }
                    let o = ((tc * 16 + yc) * 16 + xc) * 3
                    cube[o] = l * inv; cube[o + 1] = a * inv
                    cube[o + 2] = b * inv
                }
            }
        }

        // one representative gene per phase class
        let reps: [Int] = [0, 1, 2].compactMap { phase in
            (0 ..< SKGeneWeights.geneCount).first {
                SKGeneWeights.genePhase[$0] == Int32(phase) }
        }
        guard reps.count == 3 else { return nil }

        var parts: [String] = []
        for (ci, g) in reps.enumerated() {
            var hits: [Int32: Int] = [:]
            var disp: Float = 0
            var count = 0
            for bt in 0 ..< 8 {
                for by in 0 ..< 8 {
                    for bx in 0 ..< 8 {
                        var block = [(Float, Float, Float)]()
                        block.reserveCapacity(8)
                        for dt in 0 ..< 2 {
                            for dy in 0 ..< 2 {
                                for dx in 0 ..< 2 {
                                    let o = (((2 * bt + dt) * 16
                                              + 2 * by + dy) * 16
                                             + 2 * bx + dx) * 3
                                    block.append((cube[o], cube[o + 1],
                                                  cube[o + 2]))
                                }
                            }
                        }
                        let z0 = encode(block: block, level: 2)
                        let z1 = activate(gene: g, from: z0)
                        let zn0 = normalized(z0), zn1 = normalized(z1)
                        var d: Float = 0
                        for j in 0 ..< 24 {
                            let t = zn1[j] - zn0[j]; d += t * t
                        }
                        disp += d
                        if ci < 2 {
                            hits[nearestAttractor(z1).nf, default: 0] += 1
                        }
                        count += 1
                    }
                }
            }
            let meanDisp = disp / Float(count)
            if ci < 2 {
                let top = hits.max { $0.value < $1.value }!
                parts.append(String(
                    format: "%@ gene=%d nf=%d hit=%.3f disp=%.4f",
                    ci == 0 ? "order" : "boundary",
                    SKGeneWeights.geneID[g], top.key,
                    Float(top.value) / Float(count), meanDisp))
            } else {
                parts.append(String(
                    format: "chaos gene=%d disp=%.4f",
                    SKGeneWeights.geneID[g], meanDisp))
            }
        }
        return "SK GENES v1 blocks=512 " + parts.joined(separator: " | ")
    }
}
